baseURL = "https://example.org"
title = "Derrick Wells â€“ Independent Product Designer"
description = "Passionate designer curating designs for new startups  and  founders  and crafts  beautiful user interfaces with love."
theme = "hugo-derrick"
themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "derrick"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Derrick Wells"
  job = "Independent Product Designer"
  bio = "Passionate designer curating designs for new startups  and  founders  and crafts  beautiful user interfaces with love."
  email = "forexample@website.com"

[[menu.footer]]
  weight = 1
  name = "Twitter"
  url = "https://twitter.com/"

[[menu.footer]]
  weight = 2
  name = "Facebook"
  url = "https://facebook.com/"

[[menu.footer]]
  weight = 3
  name = "Instagram"
  url = "https://instagram.com/"